import type { Moment, CalendarEntry, PostDraft, BenchmarkEntry } from '@/types';
import { generateId, getDayName } from '@/lib/utils';

// In-memory stores — replace with Cloudflare D1 later
export const momentsStore = new Map<string, Moment>();
export const calendarStore = new Map<string, CalendarEntry>();
export const postStore = new Map<string, PostDraft>();

export let scraperStatus = {
  lastScrapedAt: null as string | null,
  isRunning: false,
  byPlatform: {} as Record<string, number>,
};

// ─── Historical seed data (Jan, Feb, Mar 2026) ────────────────────────────────
const HISTORICAL_MOMENTS: Omit<Moment, 'id' | 'createdAt'>[] = [
  // ── January 2026 ──────────────────────────────────────────────────────────
  {
    name: 'IPL 2026 Mega Auction',
    description: 'IPL mega auction kicks off with record-breaking bids. Teams splurge on star players ahead of the new season. • Google Trends • 500,000+ searches',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Google', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop',
    trendingScore: 97,
    date: '2026-01-14',
    isCustom: false,
    tags: ['ipl', 'cricket', 'auction', 'sports'],
  },
  {
    name: 'Makar Sankranti Kite Festival 2026',
    description: 'Makar Sankranti celebrations light up skies across India. Massive kite festivals in Ahmedabad, Jaipur trending nationwide. • Google • 200,000+ searches',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2026-01-14',
    isCustom: false,
    tags: ['makarsankranti', 'festival', 'india', 'kite'],
  },
  {
    name: 'Pushpa 3 Trailer — 50M Views in 24 Hours',
    description: 'Pushpa 3 trailer released — Allu Arjun\'s return breaks YouTube records with 50M views in 24 hours. Fans flood social media with reactions and memes.',
    type: 'Fluid',
    category: 'Movies',
    priority: 'High',
    platforms: ['YouTube', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop',
    trendingScore: 96,
    date: '2026-01-08',
    isCustom: false,
    tags: ['pushpa3', 'bollywood', 'alluarjun', 'trailer'],
  },
  {
    name: 'Republic Day Parade 2026',
    description: 'India\'s Republic Day parade showcases advanced defence tech, cultural tableaux. PM Modi leads celebrations at Kartavya Path. • Google • 1M+ searches',
    type: 'Fixed',
    category: 'Politics',
    priority: 'High',
    platforms: ['Google', 'YouTube', 'Twitter', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&auto=format&fit=crop',
    trendingScore: 95,
    date: '2026-01-26',
    isCustom: false,
    tags: ['republicday', 'india', 'parade', 'nationalday'],
  },
  {
    name: 'Virat Kohli 50th ODI Century — World Record',
    description: 'Virat Kohli scores his 50th ODI century — a world record. Instagram explodes with 40M+ likes on his post. Brands rush to congratulate. • Instagram',
    type: 'Fluid',
    category: 'Sports',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19212a4b423f?w=800&auto=format&fit=crop',
    trendingScore: 99,
    date: '2026-01-19',
    isCustom: false,
    tags: ['viratkohli', 'cricket', 'record', 'sports'],
  },
  {
    name: 'Deepika Padukone x Louis Vuitton Campaign',
    description: 'Deepika launches global luxury campaign for Louis Vuitton. Her Instagram reel hits 20M views in 12 hours. Brand collab of the year trending worldwide.',
    type: 'Brand',
    category: 'Fashion',
    priority: 'High',
    platforms: ['Instagram', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-01-10',
    isCustom: false,
    tags: ['deepika', 'fashion', 'luxury', 'campaign'],
  },
  {
    name: 'Union Budget 2026 — Zero Tax Under ₹15 Lakh',
    description: 'Union Budget 2026 drops — zero tax up to ₹15 lakh income. Massive trending across all platforms. Brands pivot to "new era of spending" campaigns.',
    type: 'Fixed',
    category: 'Finance',
    priority: 'High',
    platforms: ['Google', 'Reddit', 'Twitter', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop',
    trendingScore: 97,
    date: '2026-01-31',
    isCustom: false,
    tags: ['budget2026', 'tax', 'finance', 'india'],
  },
  {
    name: 'Pongal 2026 — Tamil Nadu Festivities Go Viral',
    description: 'Pongal celebrations explode on social media — traditional kolam designs, jallikattu, sugarcane rituals trending. South India brands capitalize massively.',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop',
    trendingScore: 85,
    date: '2026-01-14',
    isCustom: false,
    tags: ['pongal', 'festival', 'tamilnadu', 'traditional'],
  },
  {
    name: 'Samsung Galaxy S26 Ultra vs iPhone 17 Pro',
    description: 'Samsung Galaxy S26 Ultra vs iPhone 17 Pro comparison floods YouTube and Reddit. AI camera features dominate tech conversation. • Reddit • YouTube • 91M views',
    type: 'Fluid',
    category: 'Tech',
    priority: 'High',
    platforms: ['YouTube', 'Reddit', 'Google', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop',
    trendingScore: 91,
    date: '2026-01-22',
    isCustom: false,
    tags: ['samsung', 'apple', 'smartphone', 'tech'],
  },
  {
    name: 'Ranveer Singh x Myntra — "India Ka Style"',
    description: 'Ranveer Singh launches Myntra\'s massive Republic Day fashion sale campaign. Ads flood Instagram and Facebook. Reel hits 25M views. Brand campaign of the month.',
    type: 'Brand',
    category: 'Fashion',
    priority: 'Medium',
    platforms: ['Instagram', 'Facebook', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&auto=format&fit=crop',
    trendingScore: 82,
    date: '2026-01-24',
    isCustom: false,
    tags: ['ranveersingh', 'myntra', 'fashion', 'campaign'],
  },
  {
    name: 'Coldplay India Tour 2026 — Tickets Sell Out',
    description: 'Coldplay announces 5 more India concert dates — all sell out in 4 minutes. BookMyShow crashes. Twitter trends #ColdplayIndia for 48 hours straight.',
    type: 'Fluid',
    category: 'Music',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop',
    trendingScore: 94,
    date: '2026-01-05',
    isCustom: false,
    tags: ['coldplay', 'music', 'concert', 'india'],
  },
  {
    name: 'BGMI 3.0 Update — 10M Installs Week 1',
    description: 'BGMI 3.0 drops with new Karakin map and ranked season. 10M installs in week 1. Gaming Twitter explodes. Brands target Gen Z gamers with in-game campaigns.',
    type: 'Fluid',
    category: 'Gaming',
    priority: 'Medium',
    platforms: ['YouTube', 'Reddit', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&auto=format&fit=crop',
    trendingScore: 80,
    date: '2026-01-12',
    isCustom: false,
    tags: ['bgmi', 'gaming', 'battlegrounds', 'mobile'],
  },
  {
    name: 'Priyanka Chopra Netflix India Original Teaser',
    description: 'Priyanka Chopra Jonas drops teaser for her new Netflix India original series. 100M impressions on Instagram in 24 hours. Global × local marketing moment.',
    type: 'Fluid',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Instagram', 'YouTube', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&auto=format&fit=crop',
    trendingScore: 89,
    date: '2026-01-29',
    isCustom: false,
    tags: ['priyankachopra', 'netflix', 'series', 'entertainment'],
  },
  {
    name: 'Zomato Secondary Offering — 180x Subscribed',
    description: 'Zomato\'s secondary offering subscribed 180x. Retail investors flood Zerodha, Groww. Finance Twitter ablaze with analysis threads. • Reddit • Twitter',
    type: 'Fluid',
    category: 'Finance',
    priority: 'Medium',
    platforms: ['Twitter', 'Reddit', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop',
    trendingScore: 83,
    date: '2026-01-16',
    isCustom: false,
    tags: ['zomato', 'ipo', 'stock', 'finance'],
  },
  {
    name: '#WinterWellness Immunity Shots Trend',
    description: 'Influencer-led immunity shot trend floods Instagram Reels. #WinterWellness racks 500M views. Health brands see 3x spike in DM inquiries. • Instagram • YouTube',
    type: 'Fluid',
    category: 'Health',
    priority: 'Medium',
    platforms: ['Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop',
    trendingScore: 76,
    date: '2026-01-07',
    isCustom: false,
    tags: ['wellness', 'health', 'fitness', 'winter'],
  },

  {
    name: 'Lohri 2026',
    description: 'Lohri celebrations light up Punjab and North India with bonfires and bhangra. Instagram Reels of bonfire dances rack up 80M+ views. Brands ride the festive warmth wave. • Google • Instagram • 150,000+ searches',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-01-13',
    isCustom: false,
    tags: ['lohri', 'festival', 'punjab', 'winter'],
  },
  {
    name: 'Army Day India',
    description: 'Indian Army Day honours the nation\'s soldiers. Defence-related content surges across Google and Twitter. Brands show solidarity with patriotic campaigns. • Google • Twitter • 80,000+ searches',
    type: 'Fixed',
    category: 'Politics',
    priority: 'Medium',
    platforms: ['Google', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?w=800&auto=format&fit=crop',
    trendingScore: 72,
    date: '2026-01-15',
    isCustom: false,
    tags: ['armyday', 'india', 'military', 'defence'],
  },
  {
    name: 'Subhas Chandra Bose Jayanti',
    description: 'Netaji\'s birth anniversary sparks patriotic content and tributes across social media. Freedom fighter nostalgia trends on Google, Twitter and Facebook. • Google • 70,000+ searches',
    type: 'Fixed',
    category: 'Politics',
    priority: 'Medium',
    platforms: ['Google', 'Twitter', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1562619371-b67725b6fde2?w=800&auto=format&fit=crop',
    trendingScore: 70,
    date: '2026-01-23',
    isCustom: false,
    tags: ['netaji', 'freedomfighter', 'india'],
  },
  {
    name: 'National Tourism Day',
    description: 'National Tourism Day spotlights India\'s incredible destinations. Travel influencers flood Instagram with hidden gems. Niche opportunity for travel and hospitality brands. • Google • Instagram',
    type: 'Fixed',
    category: 'Travel',
    priority: 'Low',
    platforms: ['Google', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop',
    trendingScore: 35,
    date: '2026-01-25',
    isCustom: false,
    tags: ['tourism', 'travel', 'india', 'explore'],
  },
  {
    name: 'Indian Science Congress 2026',
    description: 'Indian Science Congress kicks off with keynotes on AI and space tech. Niche but engaged audience on Google and Twitter. Tech and edu brands can ride the wave. • Google • Twitter',
    type: 'Fixed',
    category: 'Tech',
    priority: 'Low',
    platforms: ['Google', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop',
    trendingScore: 30,
    date: '2026-01-03',
    isCustom: false,
    tags: ['science', 'research', 'india', 'tech'],
  },

  // ── February 2026 ─────────────────────────────────────────────────────────
  {
    name: 'Super Bowl LX 2026',
    description: 'Super Bowl LX delivers legendary halftime show and ads that break the internet. Global ad conversation peaks. Brands drop $7M/30s spots. • YouTube • Twitter • 300M+ viewers',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['YouTube', 'Twitter', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop',
    trendingScore: 92,
    date: '2026-02-08',
    isCustom: false,
    tags: ['superbowl', 'nfl', 'sports', 'usa'],
  },
  {
    name: 'World Cancer Day 2026',
    description: 'World Cancer Day raises awareness across platforms. Health and pharma brands share stories of hope and resilience. Niche but meaningful engagement. • Google • Twitter',
    type: 'Fixed',
    category: 'Health',
    priority: 'Low',
    platforms: ['Google', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&auto=format&fit=crop',
    trendingScore: 38,
    date: '2026-02-04',
    isCustom: false,
    tags: ['cancer', 'health', 'awareness'],
  },
  {
    name: 'Basant Panchami 2026',
    description: 'Basant Panchami marks the arrival of spring. Saraswati Puja trending across North India. Education and stationery brands see engagement spike. • Google • Instagram',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88df5691cc3e?w=800&auto=format&fit=crop',
    trendingScore: 65,
    date: '2026-02-12',
    isCustom: false,
    tags: ['basantpanchami', 'festival', 'spring', 'saraswati'],
  },
  {
    name: 'MWC Barcelona 2026',
    description: 'Mobile World Congress 2026 showcases 6G, foldable phones, AI wearables. Tech Twitter explodes with hands-on reviews and product reveals. • Google • YouTube • Twitter',
    type: 'Fixed',
    category: 'Tech',
    priority: 'Medium',
    platforms: ['Google', 'YouTube', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop',
    trendingScore: 75,
    date: '2026-02-23',
    isCustom: false,
    tags: ['mwc', 'mobile', 'tech', '5g'],
  },
  {
    name: 'Maha Shivaratri 2026',
    description: 'Maha Shivaratri celebrations trend nationwide with temple visits and spiritual content. Instagram Reels of Shiva temples rack up 200M+ views. • Google • Instagram',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&auto=format&fit=crop',
    trendingScore: 78,
    date: '2026-02-26',
    isCustom: false,
    tags: ['shivaratri', 'festival', 'shiva', 'india'],
  },
  {
    name: 'Valentine\'s Day 2026 — Brand Campaign War',
    description: 'Brands go all-in for Valentine\'s — Zomato, Cadbury, Tanishq launch viral campaigns. #ValentinesDay trends 3 days straight. Biggest brand opportunity of Q1.',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Google', 'Facebook', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&auto=format&fit=crop',
    trendingScore: 95,
    date: '2026-02-14',
    isCustom: false,
    tags: ['valentines', 'campaign', 'love', 'marketing'],
  },
  {
    name: 'India vs Pakistan — ICC Champions Trophy',
    description: 'India vs Pakistan ICC Champions Trophy semi-final — 600M+ watched globally. Brands go dark for the match. Social media breaks all viewership records.',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'Google', 'Instagram', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop',
    trendingScore: 100,
    date: '2026-02-22',
    isCustom: false,
    tags: ['india', 'pakistan', 'cricket', 'icc'],
  },
  {
    name: 'Bumrah Hat-trick — Champions Trophy Hero',
    description: 'Bumrah\'s hat-trick vs England in CT semi-final becomes most-watched cricket moment of 2026. 15M+ reels shared. Nike India drops instant congratulation ad.',
    type: 'Fluid',
    category: 'Sports',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800&auto=format&fit=crop',
    trendingScore: 98,
    date: '2026-02-18',
    isCustom: false,
    tags: ['bumrah', 'cricket', 'hatrick', 'sports'],
  },
  {
    name: 'AR Rahman Grammy Win 2026',
    description: 'AR Rahman wins his third Grammy for "Spirit of India" — global moment. India trends worldwide. Brands rush to celebrate India\'s music pride. • Twitter • Google',
    type: 'Fluid',
    category: 'Music',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2026-02-02',
    isCustom: false,
    tags: ['arrahman', 'grammy', 'music', 'india'],
  },
  {
    name: 'Swiggy vs Zomato Valentine\'s Meme War',
    description: 'Swiggy and Zomato engage in a legendary Twitter meme war on Valentine\'s — "single and delivering" vs "deliver your love". Goes globally viral. • Twitter • Reddit',
    type: 'Fluid',
    category: 'Marketing',
    priority: 'Medium',
    platforms: ['Twitter', 'Reddit', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=800&auto=format&fit=crop',
    trendingScore: 87,
    date: '2026-02-13',
    isCustom: false,
    tags: ['swiggy', 'zomato', 'meme', 'marketing'],
  },

  // ── March 2026 ────────────────────────────────────────────────────────────
  {
    name: 'IPL 2026 Season Start',
    description: 'IPL 2026 kicks off with a blockbuster opening ceremony. 400M+ viewers on Day 1. Every brand activates cricket campaigns. Social media breaks engagement records. • Twitter • Instagram • YouTube • Google',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'YouTube', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&auto=format&fit=crop',
    trendingScore: 98,
    date: '2026-03-27',
    isCustom: false,
    tags: ['ipl', 'cricket', 'season', 'sports'],
  },
  {
    name: 'World Wildlife Day',
    description: 'World Wildlife Day brings conservation stories to social media. Nature photographers and wildlife NGOs trend. Niche but passionate community. • Google • Twitter',
    type: 'Fixed',
    category: 'Health',
    priority: 'Low',
    platforms: ['Google', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&auto=format&fit=crop',
    trendingScore: 28,
    date: '2026-03-03',
    isCustom: false,
    tags: ['wildlife', 'conservation', 'nature'],
  },
  {
    name: 'ISRO Gaganyaan Update 2026',
    description: 'ISRO announces Gaganyaan crew mission timeline. India\'s space ambitions trend on tech Twitter. Science and edu brands ride the wave. • Google • Twitter • YouTube',
    type: 'Fluid',
    category: 'Tech',
    priority: 'High',
    platforms: ['Google', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop',
    trendingScore: 85,
    date: '2026-03-15',
    isCustom: false,
    tags: ['isro', 'gaganyaan', 'space', 'india'],
  },
  {
    name: 'RRR 2 Announcement',
    description: 'Rajamouli announces RRR 2 with a teaser poster. 100M impressions in 12 hours. Tollywood and Bollywood fans go berserk. Biggest movie announcement of Q1. • YouTube • Twitter • Instagram',
    type: 'Fluid',
    category: 'Movies',
    priority: 'High',
    platforms: ['YouTube', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=800&auto=format&fit=crop',
    trendingScore: 90,
    date: '2026-03-25',
    isCustom: false,
    tags: ['rrr2', 'rajamouli', 'tollywood', 'movie'],
  },
  {
    name: 'Holi 2026 — Brands Paint India',
    description: 'Holi 2026 colour campaigns dominate every platform. Fevicol, Amul, Cadbury drop iconic ads. #PlayWithColours trends for 5 days globally. • Google • Instagram',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Instagram', 'Google', 'Facebook', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop',
    trendingScore: 96,
    date: '2026-03-20',
    isCustom: false,
    tags: ['holi', 'festival', 'colours', 'india'],
  },
  {
    name: 'Women\'s Day 2026 — #SheCan Goes Viral',
    description: '#SheCan campaign dominates IWD 2026. Nike, Titan, Nykaa win with authentic content. Over 2B impressions worldwide. Brands that missed it trended for wrong reasons.',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop',
    trendingScore: 91,
    date: '2026-03-08',
    isCustom: false,
    tags: ['womensday', 'shecan', 'campaign', 'empowerment'],
  },

  // ── Brand Moments ─────────────────────────────────────────────────────────
  {
    name: 'Zomato "Did Someone Say" Campaign',
    description: 'Zomato\'s iconic "Did Someone Say?" campaign goes hyper-viral on Twitter. The brand\'s witty reply to celebrity tweets drives 500M+ impressions. Real-time marketing at its best.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
    trendingScore: 91,
    date: '2026-01-18',
    isCustom: false,
    tags: ['zomato', 'brand', 'campaign', 'viral'],
  },
  {
    name: 'Amul Topical — Budget 2026 Creative',
    description: 'Amul\'s iconic topical ad on Union Budget 2026 goes viral. The butter brand\'s witty take on zero tax under ₹15 lakh becomes the most shared post of the week. • Instagram • Twitter',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f5a11d?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-02-01',
    isCustom: false,
    tags: ['amul', 'topical', 'budget', 'brand'],
  },
  {
    name: 'Fevicol Republic Day Ad 2026',
    description: 'Fevicol\'s minimalist Republic Day creative — "Ek Desh. Ek Bond." — wins Ad of the Day on LinkedIn. Creative Twitter erupts with appreciation. Brand equity soars.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'Medium',
    platforms: ['Instagram', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&auto=format&fit=crop',
    trendingScore: 80,
    date: '2026-01-26',
    isCustom: false,
    tags: ['fevicol', 'republicday', 'brand', 'creative'],
  },
  {
    name: 'Swiggy Instamart "2 Minutes" Challenge',
    description: 'Swiggy Instamart launches the "2 Minutes" delivery challenge. Influencers time their orders live. Campaign generates 1B+ views across platforms. Category-defining moment.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'YouTube', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
    trendingScore: 89,
    date: '2026-02-10',
    isCustom: false,
    tags: ['swiggy', 'instamart', 'challenge', 'brand'],
  },
  {
    name: 'Tanishq Holi "Colours of Love" Campaign',
    description: 'Tanishq\'s Holi campaign "Colours of Love" celebrates diversity. The emotional film wins Best Ad of Q1 at Goafest 2026. 500M+ views, 2M+ shares. Gold standard for topical jewellery marketing.',
    type: 'Brand',
    category: 'Fashion',
    priority: 'High',
    platforms: ['YouTube', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&auto=format&fit=crop',
    trendingScore: 86,
    date: '2026-03-18',
    isCustom: false,
    tags: ['tanishq', 'holi', 'jewellery', 'brand'],
  },
  {
    name: 'Apple iPhone 17 India Launch Campaign',
    description: 'Apple India launches iPhone 17 with a stunning "Shot on iPhone" campaign featuring Indian landscapes. AR billboards in Mumbai. Every tech creator covers it. • YouTube • Instagram • Twitter',
    type: 'Brand',
    category: 'Tech',
    priority: 'High',
    platforms: ['YouTube', 'Instagram', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2026-02-20',
    isCustom: false,
    tags: ['apple', 'iphone', 'launch', 'brand'],
  },
  {
    name: 'Flipkart Big Billion Days 2026',
    description: 'Flipkart\'s Big Billion Days 2026 breaks its own record — ₹10,000 Cr GMV in 24 hours. Celebrity endorsements flood Instagram. Brand conversations dominate Twitter for 5 days.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop',
    trendingScore: 92,
    date: '2026-03-10',
    isCustom: false,
    tags: ['flipkart', 'bigbilliondays', 'ecommerce', 'brand'],
  },
  {
    name: 'Cadbury Celebrations — IPL "Meetha Moment"',
    description: 'Cadbury Celebrations\' IPL 2026 "Meetha Moment" campaign — every six gets a sweet delivery offer. Real-time integration with match feed. 200M+ engagements. Benchmark brand-sports collab.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800&auto=format&fit=crop',
    trendingScore: 87,
    date: '2026-04-02',
    isCustom: false,
    tags: ['cadbury', 'ipl', 'brand', 'campaign'],
  },
  {
    name: 'Nykaa "Own Your Glow" Campaign',
    description: 'Nykaa\'s Women\'s Day "Own Your Glow" campaign features real women of all backgrounds. Goes massively viral — 50M+ views, 5M+ saves on Instagram. Sets new standard for beauty brand inclusivity.',
    type: 'Brand',
    category: 'Fashion',
    priority: 'High',
    platforms: ['Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop',
    trendingScore: 85,
    date: '2026-03-08',
    isCustom: false,
    tags: ['nykaa', 'womensday', 'beauty', 'brand'],
  },
  {
    name: 'Tata Motors "Electric India" Campaign',
    description: 'Tata Motors\' "Electric India" campaign — featuring EV road trips across 10 states — dominates YouTube. 100M+ views. EV conversation peaks. Nexon EV waitlist hits 2 lakh units.',
    type: 'Brand',
    category: 'Tech',
    priority: 'Medium',
    platforms: ['YouTube', 'Instagram', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop',
    trendingScore: 78,
    date: '2026-01-22',
    isCustom: false,
    tags: ['tata', 'ev', 'electric', 'brand'],
  },

  // ── May 2026 (Predicted) ─────────────────────────────────────────────────
  {
    name: 'Cannes Film Festival 2026',
    description: 'Cannes 2026 red carpet dominates Instagram. Indian cinema representation grows. Fashion and luxury brands activate globally. • Instagram • Twitter • YouTube',
    type: 'Fixed',
    category: 'Movies',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-05-12',
    isCustom: false,
    tags: ['cannes', 'film', 'festival', 'cinema'],
  },
  {
    name: 'Mother\'s Day 2026',
    description: 'Mother\'s Day brand campaigns flood every platform. Emotional storytelling wins — Cadbury, Tanishq, Amazon lead. Biggest gifting moment of Q2. • Instagram • Facebook • Google',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Facebook', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1518453025-d8dae0b9a4f1?w=800&auto=format&fit=crop',
    trendingScore: 90,
    date: '2026-05-10',
    isCustom: false,
    tags: ['mothersday', 'love', 'family', 'campaign'],
  },
  {
    name: 'Buddha Purnima 2026',
    description: 'Buddha Purnima brings spiritual and wellness content to the forefront. Meditation apps and wellness brands see engagement spike. • Google • Instagram',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Google', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop',
    trendingScore: 60,
    date: '2026-05-01',
    isCustom: false,
    tags: ['buddhapurnima', 'festival', 'peace'],
  },

  // ── June 2026 (Predicted) ────────────────────────────────────────────────
  {
    name: 'World Environment Day 2026',
    description: 'World Environment Day drives sustainability conversations. Brands showcase green initiatives. #ActNow trends globally. • Google • Twitter • Instagram',
    type: 'Fixed',
    category: 'Health',
    priority: 'Medium',
    platforms: ['Google', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop',
    trendingScore: 55,
    date: '2026-06-05',
    isCustom: false,
    tags: ['environment', 'sustainability', 'green'],
  },
  {
    name: 'Father\'s Day 2026',
    description: 'Father\'s Day campaigns trend with heartfelt storytelling. Brands compete for emotional resonance. Gifting and lifestyle brands see massive spike. • Instagram • Facebook • Google',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Facebook', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1591348278863-a8fb3887e2aa?w=800&auto=format&fit=crop',
    trendingScore: 85,
    date: '2026-06-21',
    isCustom: false,
    tags: ['fathersday', 'love', 'family', 'campaign'],
  },
  {
    name: 'FIFA World Cup 2026 Qualifiers',
    description: 'FIFA World Cup 2026 qualifiers heat up globally. Football content dominates YouTube and Twitter. Sportswear and beverage brands activate massively. • Twitter • YouTube • Google',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'YouTube', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop',
    trendingScore: 95,
    date: '2026-06-10',
    isCustom: false,
    tags: ['fifa', 'worldcup', 'football', 'qualifiers'],
  },

  // ── July 2026 (Predicted) ────────────────────────────────────────────────
  {
    name: 'Wimbledon Finals 2026',
    description: 'Wimbledon finals captivate global sports fans. Tennis fashion and luxury brand activations peak. • Twitter • YouTube • Google',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'YouTube', 'Google'],
    imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-07-12',
    isCustom: false,
    tags: ['wimbledon', 'tennis', 'finals', 'sports'],
  },
  {
    name: 'Amazon Prime Day 2026',
    description: 'Amazon Prime Day 2026 drives massive e-commerce conversation. Deal-hunting trends on Twitter and Reddit. Brands compete for featured slots. • Google • Twitter • Instagram',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Google', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop',
    trendingScore: 92,
    date: '2026-07-15',
    isCustom: false,
    tags: ['primeday', 'amazon', 'deals', 'shopping'],
  },

  // ── August 2026 (Predicted) ──────────────────────────────────────────────
  {
    name: 'Independence Day India 2026',
    description: 'India\'s Independence Day — PM addresses the nation. Patriotic campaigns dominate every platform. Biggest national moment of the year. • Google • Twitter • Instagram • Facebook',
    type: 'Fixed',
    category: 'Politics',
    priority: 'High',
    platforms: ['Google', 'Twitter', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&auto=format&fit=crop',
    trendingScore: 97,
    date: '2026-08-15',
    isCustom: false,
    tags: ['independenceday', 'india', 'freedom', 'national'],
  },
  {
    name: 'Raksha Bandhan 2026',
    description: 'Raksha Bandhan drives massive gifting and emotional content. E-commerce and FMCG brands see 5x engagement. #RakhiSpecial trends for 3 days. • Google • Instagram • Facebook',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    trendingScore: 90,
    date: '2026-08-08',
    isCustom: false,
    tags: ['rakshabandhan', 'festival', 'siblings', 'love'],
  },
  {
    name: 'Ganesh Chaturthi 2026',
    description: 'Ganesh Chaturthi celebrations flood social media. Mumbai\'s Lalbaugcha Raja goes viral. Food, fashion and lifestyle brands create Ganpati-themed campaigns. • Google • Instagram • YouTube • Facebook',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'YouTube', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2026-08-27',
    isCustom: false,
    tags: ['ganeshchaturthi', 'festival', 'ganpati', 'india'],
  },

  // ── September 2026 (Predicted) ───────────────────────────────────────────
  {
    name: 'iPhone 18 Launch',
    description: 'Apple unveils iPhone 18 with revolutionary AI features. Tech Twitter and YouTube explode with reviews and comparisons. Massive consumer tech moment. • YouTube • Twitter • Google • Reddit',
    type: 'Fluid',
    category: 'Tech',
    priority: 'High',
    platforms: ['YouTube', 'Twitter', 'Google', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&auto=format&fit=crop',
    trendingScore: 94,
    date: '2026-09-15',
    isCustom: false,
    tags: ['iphone', 'apple', 'launch', 'tech'],
  },
  {
    name: 'Navratri 2026',
    description: 'Navratri garba nights go viral on Instagram Reels. Fashion brands drop festive collections. 9-day celebration drives sustained engagement. • Google • Instagram • Facebook',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1604880934760-73d91ee4b5b1?w=800&auto=format&fit=crop',
    trendingScore: 91,
    date: '2026-09-28',
    isCustom: false,
    tags: ['navratri', 'festival', 'garba', 'dandiya'],
  },

  // ── October 2026 (Predicted) ─────────────────────────────────────────────
  {
    name: 'Dussehra 2026',
    description: 'Dussehra Ravan Dahan visuals flood Instagram and YouTube. Victory of good over evil themed campaigns trend. Food and fashion brands activate. • Google • Instagram • Facebook',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?w=800&auto=format&fit=crop',
    trendingScore: 89,
    date: '2026-10-07',
    isCustom: false,
    tags: ['dussehra', 'festival', 'ravana', 'victory'],
  },
  {
    name: 'Diwali 2026',
    description: 'Diwali — India\'s biggest festival and THE moment marketing event of the year. Every brand goes all-in. 10B+ social impressions. Biggest ad spend week. • Google • Instagram • Facebook • YouTube • Twitter',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook', 'YouTube', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&auto=format&fit=crop',
    trendingScore: 99,
    date: '2026-10-25',
    isCustom: false,
    tags: ['diwali', 'festival', 'lights', 'india'],
  },
  {
    name: 'Halloween 2026',
    description: 'Halloween costume and party content trends on Instagram and YouTube. Growing in India among Gen Z. Costume, food and entertainment brands activate. • Instagram • Google • YouTube',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Instagram', 'Google', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=800&auto=format&fit=crop',
    trendingScore: 70,
    date: '2026-10-31',
    isCustom: false,
    tags: ['halloween', 'spooky', 'costume', 'party'],
  },

  // ── November 2026 (Predicted) ────────────────────────────────────────────
  {
    name: 'Black Friday 2026',
    description: 'Black Friday deals dominate global e-commerce conversation. Indian brands join with massive discounts. Deal-hunting trends everywhere. • Google • Twitter • Instagram',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Google', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2026-11-27',
    isCustom: false,
    tags: ['blackfriday', 'deals', 'shopping', 'sale'],
  },
  {
    name: 'ICC T20 World Cup 2026',
    description: 'ICC T20 World Cup 2026 captivates cricket-crazy nations. India vs rivals matches break all social media records. Brands go all-in on cricket campaigns. • Twitter • YouTube • Google • Instagram',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'YouTube', 'Google', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19212a4b423f?w=800&auto=format&fit=crop',
    trendingScore: 96,
    date: '2026-11-15',
    isCustom: false,
    tags: ['t20worldcup', 'cricket', 'icc', 'sports'],
  },

  // ── December 2026 (Predicted) ────────────────────────────────────────────
  {
    name: 'Christmas 2026',
    description: 'Christmas campaigns light up social media globally. Gifting, travel and food brands see peak engagement. #MerryChristmas trends worldwide. • Google • Instagram • Facebook • YouTube',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Google', 'Instagram', 'Facebook', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800&auto=format&fit=crop',
    trendingScore: 90,
    date: '2026-12-25',
    isCustom: false,
    tags: ['christmas', 'holiday', 'festive', 'celebration'],
  },
  {
    name: 'New Year Campaign Season 2027',
    description: 'New Year\'s Eve and 2027 resolutions dominate social media. Year-in-review content goes viral. Brands drop "new year, new you" campaigns. Biggest campaign window of Q4. • Instagram • Google • Facebook • Twitter',
    type: 'Fixed',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Instagram', 'Google', 'Facebook', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2026-12-31',
    isCustom: false,
    tags: ['newyear', '2027', 'celebration', 'campaign'],
  },
];

function seedHistoricalData() {
  for (const m of HISTORICAL_MOMENTS) {
    const prefix = m.date && m.date >= '2026-05' ? 'pred_' : 'hist_';
    const id = `${prefix}${m.name.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 40)}`;
    if (!momentsStore.has(id)) {
      momentsStore.set(id, {
        ...m,
        id,
        createdAt: m.date ? new Date(m.date).toISOString() : new Date().toISOString(),
      });
    }
  }
}

// Seed historical data on module load
seedHistoricalData();

// Trigger live scrape on first server import (deferred to avoid circular deps)
let startupScheduled = false;
export function scheduleStartupScrape() {
  if (startupScheduled) return;
  startupScheduled = true;
  setImmediate(() => {
    import('@/server/scrapers/index').then(({ runOnStartup }) => runOnStartup());
  });
}

scheduleStartupScrape();

export function getMoments(): Moment[] {
  return Array.from(momentsStore.values()).sort(
    (a, b) => b.trendingScore - a.trendingScore,
  );
}

export function getCalendarEntries(): CalendarEntry[] {
  return Array.from(calendarStore.values()).sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
  );
}

export function addBenchmarkToEntry(
  calendarEntryId: string,
  benchmark: Omit<BenchmarkEntry, 'id' | 'calendarEntryId' | 'createdAt'>,
): BenchmarkEntry | null {
  const entry = calendarStore.get(calendarEntryId);
  if (!entry) return null;
  const newBenchmark: BenchmarkEntry = {
    ...benchmark,
    id: generateId(),
    calendarEntryId,
    createdAt: new Date().toISOString(),
  };
  entry.benchmarks.push(newBenchmark);
  calendarStore.set(calendarEntryId, entry);
  return newBenchmark;
}

export function removeBenchmarkFromEntry(calendarEntryId: string, benchmarkId: string): boolean {
  const entry = calendarStore.get(calendarEntryId);
  if (!entry) return false;
  entry.benchmarks = entry.benchmarks.filter(b => b.id !== benchmarkId);
  calendarStore.set(calendarEntryId, entry);
  return true;
}

export function updateBenchmarkInEntry(
  calendarEntryId: string,
  benchmarkId: string,
  patch: Partial<Omit<BenchmarkEntry, 'id' | 'calendarEntryId' | 'createdAt'>>,
): BenchmarkEntry | null {
  const entry = calendarStore.get(calendarEntryId);
  if (!entry) return null;
  const idx = entry.benchmarks.findIndex(b => b.id === benchmarkId);
  if (idx === -1) return null;
  entry.benchmarks[idx] = { ...entry.benchmarks[idx], ...patch };
  calendarStore.set(calendarEntryId, entry);
  return entry.benchmarks[idx];
}

export function addCalendarEntry(momentId: string, date: string, ownership: 'Say Hi!' | 'Small Talk' | 'Conversation' = 'Say Hi!'): CalendarEntry | null {
  const moment = momentsStore.get(momentId);
  if (!moment) return null;

  const existing = Array.from(calendarStore.values()).find(
    e => e.momentId === momentId && e.date === date,
  );
  if (existing) return existing;

  const entry: CalendarEntry = {
    id: generateId(),
    momentId,
    moment,
    date,
    day: getDayName(date),
    ownership,
    creativeBudget: 500,
    mediaBudget: 1000,
    currency: 'INR',
    benchmarks: [],
    createdAt: new Date().toISOString(),
  };
  calendarStore.set(entry.id, entry);
  return entry;
}
