import type { Moment } from '@/types';
import { generateId } from '@/lib/utils';

export const SEED_MOMENTS: Moment[] = [
  // Fixed Moments
  {
    id: generateId(),
    name: 'IPL 2025 Season Opener',
    description: 'Indian Premier League kicks off its 18th season with massive viewership expected across all platforms. Teams like MI, CSK, RCB battle for the title.',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19212a4b423f?w=800&auto=format&fit=crop',
    trendingScore: 95,
    date: '2025-03-22',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['cricket', 'ipl', 'sports'],
  },
  {
    id: generateId(),
    name: 'Holi Festival Celebrations',
    description: 'Festival of colours trending with #HappyHoli. Brands jumping on vibrant creative campaigns with colour-themed content.',
    type: 'Fixed',
    category: 'Entertainment',
    priority: 'High',
    platforms: ['Instagram', 'Facebook', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1576502200916-3808e07386a5?w=800&auto=format&fit=crop',
    trendingScore: 88,
    date: '2025-03-14',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['holi', 'festival', 'colors'],
  },
  {
    id: generateId(),
    name: 'ICC Champions Trophy',
    description: 'ICC Champions Trophy 2025 creates massive buzz as India faces off in the semifinals. #ICCChampionsTrophy trending globally.',
    type: 'Fixed',
    category: 'Sports',
    priority: 'High',
    platforms: ['Twitter', 'YouTube', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop',
    trendingScore: 92,
    date: '2025-02-19',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['cricket', 'icc', 'sports'],
  },
  {
    id: generateId(),
    name: 'Union Budget 2025',
    description: 'Finance Minister presents Union Budget 2025. Key announcements on tax slabs, infra spending trending across finance and news platforms.',
    type: 'Fixed',
    category: 'Finance',
    priority: 'High',
    platforms: ['Twitter', 'YouTube', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop',
    trendingScore: 85,
    date: '2025-02-01',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['budget', 'finance', 'economy'],
  },
  {
    id: generateId(),
    name: 'Oscars 2025',
    description: '#Oscars2025 dominating entertainment conversations worldwide. Best picture nominees and celebrity fashion creating viral content opportunities.',
    type: 'Fixed',
    category: 'Movies',
    priority: 'Medium',
    platforms: ['Twitter', 'Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=800&auto=format&fit=crop',
    trendingScore: 78,
    date: '2025-03-02',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['oscars', 'movies', 'awards'],
  },
  // Fluid Moments
  {
    id: generateId(),
    name: 'Penguin Dance Trend',
    description: 'A viral video of penguins mimicking human dance moves at a zoo sparked a global TikTok/Reels challenge. #PenguinDance has 50M+ views in 48 hours.',
    type: 'Fluid',
    category: 'Meme',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?w=800&auto=format&fit=crop',
    trendingScore: 90,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['penguin', 'viral', 'meme', 'dance'],
  },
  {
    id: generateId(),
    name: '"It Is What It Is" Meme Wave',
    description: 'The phrase "it is what it is" resurged unexpectedly after a celebrity used it in a candid interview, spawning thousands of relatable memes.',
    type: 'Fluid',
    category: 'Meme',
    priority: 'Medium',
    platforms: ['Twitter', 'Instagram', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=800&auto=format&fit=crop',
    trendingScore: 65,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['meme', 'viral', 'relatable'],
  },
  {
    id: generateId(),
    name: 'AI Art Storm',
    description: 'A new AI art style generating anime-style portraits of real people went viral overnight. Every brand page is jumping in with character versions of their mascots.',
    type: 'Fluid',
    category: 'Tech',
    priority: 'High',
    platforms: ['Instagram', 'Twitter', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop',
    trendingScore: 88,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['ai', 'art', 'viral', 'tech'],
  },
  {
    id: generateId(),
    name: 'Bollywood Unexpected Casting',
    description: 'An unexpected casting announcement for a mega Bollywood film shocked fans causing massive debates across social platforms. #BollywoodCasting trending.',
    type: 'Fluid',
    category: 'Movies',
    priority: 'Medium',
    platforms: ['Twitter', 'Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop',
    trendingScore: 72,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['bollywood', 'movies', 'casting'],
  },
  {
    id: generateId(),
    name: 'Street Food Viral Moment',
    description: 'A street vendor\'s unique cooking technique caught on camera racked up 20M views in 24 hours, inspiring food brands to recreate content.',
    type: 'Fluid',
    category: 'Food',
    priority: 'Medium',
    platforms: ['YouTube', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop',
    trendingScore: 68,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['food', 'viral', 'street food'],
  },
  {
    id: generateId(),
    name: '#MondayMotivation Wave',
    description: 'A particularly powerful Monday Motivation post chain went viral after a startup founder shared a raw, honest story about failure.',
    type: 'Fluid',
    category: 'Marketing',
    priority: 'Low',
    platforms: ['Twitter', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop',
    trendingScore: 45,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['motivation', 'monday', 'startup'],
  },
  // Brand Moments
  {
    id: generateId(),
    name: 'KitKat Chocolate Heist',
    description: 'News of a theft targeting a KitKat warehouse went viral. Brand responded with hilarious social media posts about "needing a break" — generating 10x engagement.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&auto=format&fit=crop',
    trendingScore: 87,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['kitkat', 'brand', 'marketing', 'viral'],
  },
  {
    id: generateId(),
    name: 'Zomato "How We Work" Post',
    description: 'Zomato shared a behind-the-scenes look at their logistics operation, sparking massive conversation about gig economy and delivery partner conditions.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'High',
    platforms: ['Twitter', 'Twitter', 'Instagram'],
    imageUrl: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&auto=format&fit=crop',
    trendingScore: 82,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['zomato', 'brand', 'delivery'],
  },
  {
    id: generateId(),
    name: 'Netflix India Price Hike Backlash',
    description: 'Netflix announced a subscription price increase in India, leading to widespread Twitter backlash and memes comparing it to competitors.',
    type: 'Brand',
    category: 'Entertainment',
    priority: 'Medium',
    platforms: ['Twitter', 'Reddit', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&auto=format&fit=crop',
    trendingScore: 74,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['netflix', 'brand', 'streaming'],
  },
  {
    id: generateId(),
    name: 'Amul New Flavour Launch',
    description: 'Amul launched an unexpected new ice cream flavour inspired by Indian street food, creating an online frenzy with fans sharing taste reviews.',
    type: 'Brand',
    category: 'Food',
    priority: 'Medium',
    platforms: ['Instagram', 'Facebook', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=800&auto=format&fit=crop',
    trendingScore: 61,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['amul', 'food', 'brand', 'launch'],
  },
  {
    id: generateId(),
    name: 'Byju\'s Comeback Campaign',
    description: 'Byju\'s launched a bold comeback campaign after restructuring, addressing controversies head-on with a transparency-first approach.',
    type: 'Brand',
    category: 'Marketing',
    priority: 'Low',
    platforms: ['YouTube', 'Twitter', 'Twitter'],
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop',
    trendingScore: 48,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['byjus', 'edtech', 'brand'],
  },
  // More varied moments
  {
    id: generateId(),
    name: 'Coldplay India Tour',
    description: 'Coldplay announces India leg of Music of the Spheres world tour. Ticket frenzy crashes booking sites, #ColdplayIndia trends for 3 days straight.',
    type: 'Fixed',
    category: 'Music',
    priority: 'High',
    platforms: ['Twitter', 'Instagram', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&auto=format&fit=crop',
    trendingScore: 93,
    date: '2025-01-19',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['coldplay', 'music', 'concert'],
  },
  {
    id: generateId(),
    name: 'Crypto Market Rally',
    description: 'Bitcoin and Ethereum see massive gains following regulatory clarity. #CryptoRally dominates finance Twitter and Reddit with retail investors piling in.',
    type: 'Fluid',
    category: 'Finance',
    priority: 'High',
    platforms: ['Twitter', 'Reddit', 'YouTube'],
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&auto=format&fit=crop',
    trendingScore: 80,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['crypto', 'bitcoin', 'finance'],
  },
  {
    id: generateId(),
    name: 'Viral Gym "Transformation" Trend',
    description: 'A 365-day gym transformation video garnered 100M+ views, inspiring thousands of similar content pieces and hashtag campaigns.',
    type: 'Fluid',
    category: 'Health',
    priority: 'Medium',
    platforms: ['Instagram', 'YouTube', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop',
    trendingScore: 70,
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['fitness', 'health', 'transformation'],
  },
  {
    id: generateId(),
    name: 'GTA VI Release Hype',
    description: 'Rockstar drops final GTA VI trailer ahead of release date confirmation. Gaming community explodes with content, memes, and reaction videos.',
    type: 'Fixed',
    category: 'Gaming',
    priority: 'High',
    platforms: ['YouTube', 'Twitter', 'Reddit'],
    imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&auto=format&fit=crop',
    trendingScore: 96,
    date: '2025-05-26',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['gta6', 'gaming', 'rockstar'],
  },
  {
    id: generateId(),
    name: 'Fashion Week Mumbai',
    description: 'Mumbai Fashion Week runway shows dominate Instagram with sustainable fashion stories. #FDCI trends as designers showcase eco-conscious collections.',
    type: 'Fixed',
    category: 'Fashion',
    priority: 'Medium',
    platforms: ['Instagram', 'YouTube', 'Facebook'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    trendingScore: 66,
    date: '2025-04-15',
    isCustom: false,
    createdAt: new Date().toISOString(),
    tags: ['fashion', 'runway', 'fdci'],
  },
];
